export const DISPLAY_ALERT = 'SHOW_ALERT'
export const CLEAR_ALERT = 'CLEAR_ALERT'

export const SETUP_USER_BEGIN = 'SETUP_USER_BEGIN'
export const SETUP_USER_SUCCESS = 'SETUP_USER_SUCCESS'
export const SETUP_USER_ERROR = 'SETUP_USER_ERROR'

export const SETUP_CLUB_BEGIN = 'SETUP_CLUB_BEGIN'
export const SETUP_CLUB_SUCCESS = 'SETUP_CLUB_SUCCESS'
export const SETUP_CLUB_ERROR = 'SETUP_CLUB_ERROR'

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'
export const LOGOUT_USER = 'LOGOUT_USER'
export const LOGOUT_CLUB = 'LOGOUT_CLUB'

export const UPDATE_USER_BEGIN = 'UPDATE_USER_BEGIN'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR'

export const UPDATE_CLUB_BEGIN = 'UPDATE_CLUB_BEGIN'
export const UPDATE_CLUB_SUCCESS = 'UPDATE_CLUB_SUCCESS'
export const UPDATE_CLUB_ERROR = 'UPDATE_CLUB_ERROR'

export const HANDLE_CHANGE = 'HANDLE_CHANGE'
export const CLEAR_VALUES = 'CLEAR_VALUES'

export const CREATE_PROJECT_BEGIN = 'CREATE_PROJECT_BEGIN'
export const CREATE_PROJECT_SUCCESS = 'CREATE_PROJECT_SUCCESS'
export const CREATE_PROJECT_ERROR = 'CREATE_PROJECT_ERROR'

export const GET_PROJECTS_BEGIN = 'GET_PROJECTS_BEGIN'
export const GET_PROJECTS_SUCCESS = 'GET_PROJECTS_SUCCESS'

export const SET_EDIT_PROJECT = 'SET_EDIT_PROJECT'

export const DELETE_PROJECT_BEGIN = 'DELETE_PROJECT_BEGIN'

export const EDIT_PROJECT_BEGIN = 'EDIT_PROJECT_BEGIN'
export const EDIT_PROJECT_SUCCESS = 'EDIT_PROJECT_SUCCESS'
export const EDIT_PROJECT_ERROR = 'EDIT_PROJECT_ERROR'

export const SHOW_STATS_BEGIN = 'SHOW_STATS_BEGIN'
export const SHOW_STATS_SUCCESS = 'SHOW_STATS_SUCCESS'

export const CLEARC_VALUES = 'CLEARC_VALUES'

export const CREATE_PROJECTC_BEGIN = 'CREATE_PROJECTC_BEGIN'
export const CREATE_PROJECTC_SUCCESS = 'CREATE_PROJECTC_SUCCESS'
export const CREATE_PROJECTC_ERROR = 'CREATE_PROJECTC_ERROR'

export const GET_PROJECTSC_BEGIN = 'GET_PROJECTSC_BEGIN'
export const GET_PROJECTSC_SUCCESS = 'GET_PROJECTSC_SUCCESS'

export const SET_EDITC_PROJECT = 'SET_EDITC_PROJECT'

export const DELETE_PROJECTC_BEGIN = 'DELETE_PROJECTC_BEGIN'

export const EDIT_PROJECTC_BEGIN = 'EDIT_PROJECTC_BEGIN'
export const EDIT_PROJECTC_SUCCESS = 'EDIT_PROJECTC_SUCCESS'
export const EDIT_PROJECTC_ERROR = 'EDIT_PROJECTC_ERROR'

export const SHOW_STATSC_BEGIN = 'SHOW_STATSC_BEGIN'
export const SHOW_STATSC_SUCCESS = 'SHOW_STATSC_SUCCESS'

export const CLEAR_FILTERS = 'CLEAR_FILTERS'
export const CHANGE_PAGE = 'CHANGE_PAGE'
